# Generated by Django 5.1.2 on 2024-10-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_me', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
